### ISSUE TITLE
3.2.3 Seleccionar Pago

### ISSUE THREAD

**Issue by antoniojxk** [ISWPOLI/TaxisVerdes#24]
"**como**: usuario del sistema
**quiero**: seleccionar el medio de pago que deseo 
**de forma que**: de acceder a los ticketes o reserva"

- [x] crear layout donde se muestren los medios de pago
- [x] crear evento al seleccionar uno de los medios de pago disponibles
- [x] pedir la información de la tarjeta de crédito del cliente"

**Comment by neobart10** [comment]
se implementa
